"""Agent 3 — SVG Generation.

Deterministic: the tactile scene graph fully determines the SVG, so no LLM call
is needed (and none should be — markup generated by an LLM risks drifting from
the agreed structure). Produces the tactile.svg artifact.
"""
from __future__ import annotations

from ..models import TactileDesign
from ..rendering.svg_renderer import render_svg


def run(design: TactileDesign) -> str:
    return render_svg(design)
